"""empty message

Revision ID: b928be6d5b69
Revises: 
Create Date: 2023-08-10 22:24:41.583690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b928be6d5b69'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_books_book_id', table_name='books')
    op.drop_index('ix_books_title', table_name='books')
    op.drop_index('ix_books_year', table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('book_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('book_id', name='books_pkey')
    )
    op.create_index('ix_books_year', 'books', ['year'], unique=False)
    op.create_index('ix_books_title', 'books', ['title'], unique=False)
    op.create_index('ix_books_book_id', 'books', ['book_id'], unique=False)
    # ### end Alembic commands ###
