# .github/workflows/deploy.yml
name: deploy to deta space

on:
  push:
    branches:
    - main

jobs:
  deploy:
    name: deploy to deta space
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Echo
      run: echo secrets.SPACE_ACCESS_TOKEN ${{ secrets.SPACE_ACCESS_TOKEN }} and secrets.SPACE_ID ${{ secrets.SPACE_ID }}
    - name: Deploy
      uses: lizheming/deta-action@master
      with:
        access_token: ${{ secrets.SPACE_ACCESS_TOKEN }}
        id: ${{ secrets.SPACE_ID }}
        listed: false